### ISSUE TITLE
Include example with <button> element vs <a>

### ISSUE THREAD

**Issue by adamjohnson** [scottaohara/aria_disclosure_widget#2]
Would this component work with a `<button>` tag instead of an `<a>` tag? Shouldn't these use `<button>`'s instead of `<a>`'s? 

I'm thinking of [this tweet from Zoe Bijl](https://twitter.com/ZoeBijl/status/1125707483765407744):

  > Should I use an `<a>` or a `<button>`? A basic test:
  >  a) Can you right click/tap-and-hold it to open it in a new page? → `<a>`
  >  b) If not A, does it perform an action on the current page? → `<button>`

**Comment by scottaohara** [comment]
it could likely be revised to do that.  an abandoned 1.0 branch i had been working on did use `<button>` instead of `<a>`.  But not really a huge issue in the grand scheme of things / doesn't apply to Zoe's tweet as you seem to be alluding to. The exposed role of these progressively enhanced `<a>` elements is "button" due to the `role=button` that gets applied during the build.

**Comment by scottaohara** [comment]
FWIW, thanks.  your comment got me to actually pay attention to this and just push a trimmed down version of the revised script and get rid of the previous one.

**Comment by adamjohnson** [comment]
Awesome! Thank you for your incredibly fast response. 👏
